/* Generated by build/translate-components.mjs from source/fa/components.json.
   Prose is Farsi; specimen HTML, class names and React code are untouched.
   Edit the Farsi in source/fa/components.json, then re-run the script. */
export default [
  {
    "name": "Button",
    "slug": "button",
    "group": "Actions",
    "status": "revised",
    "legacy": [
      "Button / Red / Default",
      "Button / Red / Hover",
      "Button / Red / Disable",
      "Button/‌Blue/Default + Chevron",
      "Button/‌Blue/Clicked + Chevron",
      "Button/‌Blue/Hover + Chevron",
      "Button/Black/Default",
      "Button/Black/Hover",
      "Button/Black/Disable",
      "Button/Black ghost/Default",
      "Button/Black ghost/Hover",
      "Button/‌Blue ghost/Icon/Light",
      "Button/‌Blue ghost/Icon/Dark",
      "Button/Small/Blue/with-badge",
      "Button/Xsmall/Secondary/Icon",
      "Button/Normal/Primary/Icon",
      "Button/Normal/Border/Icon"
    ],
    "summary": "یک کنش را اجرا می‌کند. در هر صفحه فقط یک دکمهٔ اصلی.",
    "description": [
      "ترب <strong>سه خانوادهٔ رنگی</strong> دارد و رنگ اینجا تزئین نیست، معنا دارد: <strong class=\"fam-red\">قرمز</strong> کنش خرید اینترنتی است، <strong class=\"fam-blue\">آبی</strong> کنش حضوری و ارتباط با فروشگاه (مسیریابی، تماس) و <strong class=\"fam-black\">مشکی</strong> خنثی. به همین دلیل است که <code>Button/Offline Buy box</code> آبی است، نه دکمهٔ خط‌دار.",
      "دو جزئیات که هر دو از اسکچ اندازه‌گیری شده و هر دو به‌راحتی از دست می‌روند. <strong>حالت پیش‌فرض گرادیان است و هاور به رنگ تخت جمع می‌شود</strong>؛ یعنی دکمه زیر نشانگر می‌نشیند، نه اینکه بالا بیاید. و هر دکمهٔ پرشده یک <strong>لبهٔ داخلی ۱ پیکسلی هم‌خانواده با خودش</strong> دارد (قرمز از Red 50، آبی از Blue 300). همین لبه است که نمی‌گذارد یک سطح رنگی اشباع، مستطیل تخت دیده شود.",
      "کیت اولیه هر حالت را یک سیمبل جدا مدل کرده بود؛ <code>Button / Red / Hover</code> کنار <code>Button / Red / Default</code> به‌عنوان مستر مستقل. این ساختار هرگز به API کامپوننت تبدیل نمی‌شود. اینجا <strong>حالت، حالت است</strong> (سودوکلاس‌های CSS و صفت‌های <code>data-</code>) و فقط خانواده و اندازه پراپ هستند.",
      "Variants are named by <strong>intent</strong>, not by colour. <code>Button / Red</code> became <code>variant=\"primary\"</code>: when the brand palette shifts, the code does not. The examples page had already started this migration on its own — <code>Button/Normal/Primary/Icon</code>, so this formalises a direction your team was already moving in."
    ],
    "use": [
      "در هر صفحه دقیقاً یک دکمهٔ <code>red</code>؛ همان کاری که کاربر برای آن آمده است.",
      "<code>blue</code> برای کنش حضوری و ارتباط با فروشگاه، <code>ghost</code> برای کنش درجه‌سه.",
      "برچسب را با فعلی بنویسید که نتیجه را نام ببرد: «مشاهده فروشندگان»، نه «بیشتر».",
      "هنگام کار ناهمگام <code>data-loading</code> بگذارید؛ برچسب پنهان می‌شود اما عرض دکمه ثابت می‌ماند."
    ],
    "avoid": [
      "دو دکمهٔ اصلی کنار هم. اگر هر دو مهم‌اند، هیچ‌کدام اصلی نیست.",
      "غیرفعال‌کردن بدون توضیح. دلیلش را کنار دکمه بنویسید.",
      "قرمز برای کنش حضوری. رنگ اینجا یک قول است، نه یک سلیقه.",
      "دکمهٔ فقط آیکون بدون <code>aria-label</code>."
    ],
    "anatomy": [
      [
        "ظرف",
        "ارتفاع، گردی ۱۲ و ناحیهٔ لمس را تعیین می‌کند. کادر بصری می‌تواند ۲۴ پیکسل باشد؛ ناحیهٔ لمس هرگز زیر ۴۴ پیکسل نمی‌رود."
      ],
      [
        "آیکون آغازین",
        "اختیاری، ۱۶ پیکسل. آیکون‌های جهت‌دار در راست‌چین قرینه می‌شوند."
      ],
      [
        "برچسب",
        "۱۴ پیکسل Bold. هرگز به خط بعد نمی‌رود؛ به‌جایش ظرف را کوتاه کنید."
      ],
      [
        "آیکون پایانی",
        "اختیاری. شورون اینجا یعنی «چیزی باز می‌شود»، نه «ثبت می‌شود»."
      ]
    ],
    "props": [
      [
        "variant",
        "'red' | 'blue' | 'black' | 'black-ghost' | 'blue-outline' | 'red-outline' | 'soft' | 'ghost' | 'blue-ghost' | 'glass'",
        "'black'",
        "خانوادهٔ رنگی. <code>primary</code>، <code>accent</code> و <code>neutral</code> نام مستعار قرمز، آبی و مشکی‌اند و در کد محصول ترجیح دارند."
      ],
      [
        "size",
        "'xs' | 'sm' | 'md' | 'lg' | 'xl'",
        "'lg'",
        "۲۴ / ۲۸ / ۳۲ / ۴۰ / ۴۸ پیکسل. <code>lg</code> پیش‌فرض است و با کیت اسکچ می‌خواند."
      ],
      [
        "block",
        "boolean",
        "false",
        "پرکردن کل محور درون‌خطی."
      ],
      [
        "loading",
        "boolean",
        "false",
        "اسپینر نشان می‌دهد، عرض را نگه می‌دارد و رویداد اشاره‌گر را می‌بندد."
      ],
      [
        "disabled",
        "boolean",
        "false",
        "همهٔ خانواده‌ها به یک ظاهر غیرفعال جمع می‌شوند."
      ],
      [
        "iconStart / iconEnd",
        "ReactNode",
        "—",
        "آیکون آغازین و پایانی به ترتیب منطقی؛ در چپ‌چین خودشان جا عوض می‌کنند."
      ]
    ],
    "a11y": [
      "یک <code>&lt;button&gt;</code> واقعی رندر می‌شود. <code>&lt;a class=\"t-btn\"&gt;</code> فقط وقتی که ناوبری می‌کند.",
      "حالت بارگذاری <code>aria-busy=\"true\"</code> می‌گذارد و نام دسترس‌پذیر ثابت می‌ماند تا صفحه‌خوان دوباره اعلام نکند.",
      "حلقهٔ فوکوس ۲ پیکسل با فاصلهٔ ۲ پیکسل است و در هر سه پوسته نسبت <span class=\"t-bidi\" dir=\"ltr\">۳:۱</span> را نگه می‌دارد (معیار ۲.۴.۱۳ نسخهٔ ۲.۲).",
      "غیرفعال با صفت <code>disabled</code>، نه با <code>pointer-events: none</code> که برای فناوری کمکی نامرئی است.",
      "برچسب غیرفعال با نسبت <span class=\"t-bidi\" dir=\"ltr\">۴٫۸:۱</span> خوانا می‌ماند؛ سیگنال غیرفعال‌بودن را سطح خاکستری و نبود لبه می‌رسانند، نه متن ناخوانا.",
      "در هر اندازه ناحیهٔ لمس دست‌کم ۴۴ پیکسل است — بسیار بالاتر از حداقل <span class=\"t-bidi\" dir=\"ltr\">۲۴×۲۴</span> در معیار ۲.۵.۸."
    ],
    "responsive": "دکمه با نقطهٔ شکست تغییر اندازه نمی‌دهد. زیر ۳۷۵ پیکسل از <code>block</code> استفاده کنید تا برچسب هرگز بریده نشود. در فوتری با دو کنش، هر دو <code>block</code> می‌شوند و زیر ۳۶۰ پیکسل روی هم می‌نشینند.",
    "specimens": [
      {
        "label": "سه خانوادهٔ رنگی",
        "note": "قرمز خرید اینترنتی است، آبی کنش فروشگاهی و مشکی خنثی. روی هر کدام هاور کنید: گرادیان به رنگ تخت جمع می‌شود.",
        "stageClass": "spec__stage--stack",
        "html": "<div style=\"display:flex;gap:12px;flex-wrap:wrap;align-items:center\">\n  <button class=\"t-btn t-btn--red\">خرید اینترنتی</button>\n  <button class=\"t-btn t-btn--blue\">اطلاعات تماس</button>\n  <button class=\"t-btn t-btn--black\">عنوان</button>\n</div>\n<div style=\"display:flex;gap:12px;flex-wrap:wrap;align-items:center\">\n  <button class=\"t-btn t-btn--red-outline\">خرید اینترنتی</button>\n  <button class=\"t-btn t-btn--blue-outline\">اطلاعات تماس</button>\n  <button class=\"t-btn t-btn--black-ghost\">عنوان</button>\n</div>\n<div style=\"display:flex;gap:12px;flex-wrap:wrap;align-items:center\">\n  <button class=\"t-btn t-btn--soft\">ذخیره</button>\n  <button class=\"t-btn t-btn--blue-ghost\">بیشتر</button>\n  <button class=\"t-btn t-btn--ghost\">انصراف</button>\n</div>"
      },
      {
        "label": "اندازه‌ها",
        "html": "<button class=\"t-btn t-btn--red t-btn--xs\">Xsmall</button>\n<button class=\"t-btn t-btn--red t-btn--sm\">Small</button>\n<button class=\"t-btn t-btn--red t-btn--md\">Medium</button>\n<button class=\"t-btn t-btn--red t-btn--lg\">Large</button>\n<button class=\"t-btn t-btn--red t-btn--xl\">XLarge</button>"
      },
      {
        "label": "حالت‌ها",
        "note": "همهٔ خانواده‌ها به یک ظاهر غیرفعال جمع می‌شوند. برچسب با نسبت <span class=\"t-bidi\" dir=\"ltr\">۴٫۸:۱</span> خوانا می‌ماند؛ سطح تخت و نبود لبه سیگنال را می‌رسانند، نه متن ناخوانا.",
        "html": "<button class=\"t-btn t-btn--red\">خرید اینترنتی</button>\n<button class=\"t-btn t-btn--red\" data-loading=\"true\">در حال ارسال</button>\n<button class=\"t-btn t-btn--red\" disabled>خرید اینترنتی</button>\n<button class=\"t-btn t-btn--blue\" disabled>اطلاعات تماس</button>\n<button class=\"t-btn t-btn--black\" disabled>عنوان</button>"
      },
      {
        "label": "همراه آیکون",
        "html": "<button class=\"t-btn t-btn--accent\">مسیریابی<svg class=\"t-icon t-icon--sm t-icon--directional\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M10 4 6 8l4 4V4z\"/></svg></button>\n<button class=\"t-btn t-btn--outline\"><svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 1a5 5 0 0 0-5 5c0 3.5 5 9 5 9s5-5.5 5-9a5 5 0 0 0-5-5zm0 7a2 2 0 1 1 0-4 2 2 0 0 1 0 4z\"/></svg>نزدیک من</button>\n<button class=\"t-btn t-btn--primary t-btn--block\">تماس با فروشگاه</button>"
      }
    ],
    "react": "import { forwardRef } from 'react';\nimport clsx from 'clsx';\n\nexport const Button = forwardRef(function Button(\n  { variant = 'neutral', size = 'lg', block, loading, disabled,\n    iconStart, iconEnd, children, className, ...rest }, ref) {\n  return (\n    <button\n      ref={ref}\n      className={clsx('t-btn', `t-btn--${variant}`, `t-btn--${size}`, block && 't-btn--block', className)}\n      data-loading={loading || undefined}\n      aria-busy={loading || undefined}\n      disabled={disabled || loading}\n      {...rest}\n    >\n      {iconStart}\n      {children}\n      {iconEnd}\n    </button>\n  );\n});"
  },
  {
    "name": "IconButton",
    "slug": "icon-button",
    "group": "Actions",
    "status": "revised",
    "legacy": [
      "Button/Icon/Icon",
      "Button/Icon/Blue Icon",
      "Button/Icon/Ghost Icon",
      "Button/Icon/Icon Rounded",
      "Button/Icon"
    ],
    "summary": "یک آیکون به‌عنوان هدف لمس. همیشه نام دسترس‌پذیر دارد.",
    "description": [
      "کیت اولیه چهار مستر داشت — <code>Icon</code>، <code>Blue Icon</code>، <code>Ghost Icon</code> و <code>Icon Rounded</code> — که فقط در پرکردن و گردی گوشه فرق داشتند. اینجا یک کامپوننت با دو پراپ.",
      "نسخهٔ شیشه‌ای همان چیزی است که یک کنترل را روی نقشه یا عکس محصول خوانا نگه می‌دارد."
    ],
    "use": [
      "نوار ابزار، گوشهٔ کارت، کنترل‌های نقشه؛ هرجا که برچسب جا نمی‌شود.",
      "روی دستگاه‌های اشاره‌گردار با تولتیپ جفت کنید.",
      "روی نقشه یا عکس از <code>glass</code> استفاده کنید تا محتوای پشت خوانا بماند."
    ],
    "avoid": [
      "آیکون تنها برای کنش ناآشنا یا مخرب. برچسب بگذارید.",
      "نشانه‌های مبهم. اگر دو آیکون کنار هم می‌توانند یک معنی بدهند، از برچسب استفاده کنید."
    ],
    "anatomy": [
      [
        "ظرف",
        "۴۸ پیکسل پیش‌فرض، ۳۲ پیکسل کوچک. مربع با گردی ۱۲ یا کاملاً گرد."
      ],
      [
        "آیکون",
        "۲۰ پیکسل، رنگ را از ظرف به ارث می‌برد."
      ]
    ],
    "props": [
      [
        "variant",
        "'ghost' | 'accent' | 'glass'",
        "'ghost'",
        "<code>glass</code> برای استفاده روی نقشه یا تصویر."
      ],
      [
        "size",
        "'sm' | 'md'",
        "'md'",
        "۳۲ / ۴۸ پیکسل."
      ],
      [
        "round",
        "boolean",
        "false",
        "گردی کامل به‌جای ۱۲."
      ],
      [
        "label",
        "string",
        "— (required)",
        "به <code>aria-label</code> تبدیل می‌شود. نسخهٔ بدون برچسب وجود ندارد."
      ]
    ],
    "a11y": [
      "<code>label</code> اجباری است و به <code>aria-label</code> نگاشت می‌شود؛ دکمهٔ آیکونی بدون نام برای کاربر صفحه‌خوان بی‌استفاده است.",
      "برای دکمهٔ دوحالته <code>aria-pressed</code> بگذارید و نام را ثابت نگه دارید («افزودن به علاقه‌مندی»)؛ فقط حالت فشرده تغییر کند."
    ],
    "responsive": "۴۸ پیکسل روی لمس، ۳۲ پیکسل روی اشاره‌گر قابل قبول است. هرگز از ۳۲ پیکسل بصری و ۴۴ پیکسل ناحیهٔ لمس پایین‌تر نروید.",
    "specimens": [
      {
        "label": "گونه‌ها",
        "html": "<button class=\"t-icon-btn\" aria-label=\"جستجو\"><svg class=\"t-icon\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M8.5 3a5.5 5.5 0 1 0 3.4 9.8l3.6 3.7 1.1-1.1-3.7-3.6A5.5 5.5 0 0 0 8.5 3zm0 1.5a4 4 0 1 1 0 8 4 4 0 0 1 0-8z\"/></svg></button>\n<button class=\"t-icon-btn t-icon-btn--accent\" aria-label=\"تماس\"><svg class=\"t-icon\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M5 3a2 2 0 0 0-2 2c0 6.6 5.4 12 12 12a2 2 0 0 0 2-2v-2.3a1 1 0 0 0-.8-1l-2.7-.5a1 1 0 0 0-1 .4l-.8 1.1a9.6 9.6 0 0 1-4.1-4.1l1.1-.8a1 1 0 0 0 .4-1l-.5-2.7a1 1 0 0 0-1-.8H5z\"/></svg></button>\n<button class=\"t-icon-btn t-icon-btn--sm\" aria-label=\"بستن\"><svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"m12.7 4.3-1-1L8 7 4.3 3.3l-1 1L7 8l-3.7 3.7 1 1L8 9l3.7 3.7 1-1L9 8z\"/></svg></button>\n<button class=\"t-icon-btn t-icon-btn--round t-icon-btn--accent\" aria-label=\"افزودن\"><svg class=\"t-icon\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M10.8 3H9.2v6.2H3v1.6h6.2V17h1.6v-6.2H17V9.2h-6.2V3z\"/></svg></button>"
      },
      {
        "label": "شیشه، روی محتوا",
        "note": "نسخهٔ شیشه‌ای همان چیزی است که کنترل را روی نقشه یا عکس محصول خوانا نگه می‌دارد.",
        "canvas": "map",
        "stageClass": "spec__stage--center",
        "html": "<button class=\"t-icon-btn t-icon-btn--glass\" aria-label=\"موقعیت من\"><svg class=\"t-icon\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"M10 6a4 4 0 1 0 0 8 4 4 0 0 0 0-8zm0 6.5a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zM10.8 1H9.2v2.1a7 7 0 0 0-6.1 6.1H1v1.6h2.1a7 7 0 0 0 6.1 6.1V19h1.6v-2.1a7 7 0 0 0 6.1-6.1H19V9.2h-2.1a7 7 0 0 0-6.1-6.1V1z\"/></svg></button>\n<button class=\"t-icon-btn t-icon-btn--glass\" aria-label=\"لایه‌های نقشه\"><svg class=\"t-icon\" viewBox=\"0 0 20 20\" fill=\"currentColor\"><path d=\"m10 2 8 4.5-8 4.5-8-4.5L10 2zm5.6 7.2L18 10.5 10 15l-8-4.5 2.4-1.3L10 12l5.6-2.8z\"/></svg></button>"
      }
    ],
    "react": "export function IconButton({ variant = 'ghost', size = 'md', round, label, children, className, ...rest }) {\n  return (\n    <button\n      className={clsx('t-icon-btn', variant !== 'ghost' && `t-icon-btn--${variant}`,\n                      size === 'sm' && 't-icon-btn--sm', round && 't-icon-btn--round', className)}\n      aria-label={label}\n      {...rest}\n    >{children}</button>\n  );\n}"
  },
  {
    "name": "BuyBoxButton",
    "slug": "buy-box-button",
    "group": "Actions",
    "status": "revised",
    "legacy": [
      "Button/Buy box/Ad",
      "Button/Buy box/Cheapest",
      "Button/Offline Buy box/Ad",
      "Badge / Ad on Buy Box"
    ],
    "summary": "هدف خرید در صفحهٔ محصول. رنگ می‌گوید اینترنتی یا حضوری.",
    "description": [
      "مخصوص ترب و تعیین‌کننده: همان ردیفی که خریدار واقعاً در صفحهٔ محصول لمس می‌کند. دقیقاً بر پایهٔ هندسهٔ اسکچ بازسازی شده — <span class=\"t-bidi\" dir=\"ltr\">۳۴۳×۷۲</span> با گردی ۱۶، پشتهٔ فروشنده و قیمت در انتهای محور و نشان «آگهی» در ابتدای آن.",
      "رنگ اینجا معنا است، نه تأکید. <strong class=\"fam-red\">قرمز</strong> فروشندهٔ اینترنتی است که همین حالا از او می‌خرید؛ <strong class=\"fam-blue\">آبی</strong> فروشندهٔ حضوری است که باید به فروشگاهش بروید. نسخهٔ فشردهٔ <span class=\"t-bidi\" dir=\"ltr\">۳۴۳×۴۴</span> با گردی ۱۲ میان‌بر «ارزان‌ترین فروشنده» است و یک برچسب وسط‌چین دارد.",
      "یک اندازه‌گیری ارزش گفتن دارد چون شبیه اشتباه به نظر می‌رسد و نیست: <strong>نام فروشنده Bold ۱۶ است و قیمت Medium ۱۶</strong>. خریدار محدودهٔ قیمت را از فهرست می‌داند؛ در این ردیف دارد انتخاب می‌کند که <em>از چه کسی</em> بخرد، پس وزن به فروشنده می‌رسد."
    ],
    "use": [
      "در صفحهٔ محصول، برای هر فروشنده یک ردیف.",
      "مبلغی را نشان دهید که خریدار می‌پردازد، همراه با واحد پول.",
      "جایگاه‌های تبلیغاتی را همیشه با نشان «آگهی» مشخص کنید؛ این یک افشای قانونی است، نه یک انتخاب سلیقه‌ای.",
      "برای فروشندهٔ حضوری آبی بگذارید تا خریدار پیش از لمس بداند این یک سفر است، نه یک پرداخت."
    ],
    "avoid": [
      "پنهان‌کردن یا تغییر ظاهر نشان آگهی برای بالابردن نرخ کلیک.",
      "استفاده به‌عنوان دکمهٔ عمومی. معنایش این است: «این را، از این فروشنده، به این قیمت بخر».",
      "بلندتر کردن قیمت از فروشنده. این تصمیمی را که در حال گرفتن است وارونه می‌کند.",
      "قرمز برای فروشندهٔ حضوری. رنگ اینجا یک قول است."
    ],
    "anatomy": [
      [
        "ظرف",
        "<span class=\"t-bidi\" dir=\"ltr\">۳۴۳×۷۲</span>، گردی ۱۶، گرادیان خانواده، لبهٔ داخلی ۱ پیکسلی هم‌خانواده."
      ],
      [
        "نشان آگهی",
        "<span class=\"t-bidi\" dir=\"ltr\">۴۵×۲۴</span>، گردی ۱۲، پرشدهٔ #D70040 با برچسب سفید Medium ۱۲. ابتدای محور."
      ],
      [
        "فروشنده",
        "Bold ۱۶. خط اصلی."
      ],
      [
        "قیمت",
        "Medium ۱۶، ارقام جدولی، اعداد فارسی."
      ],
      [
        "فشرده",
        "<span class=\"t-bidi\" dir=\"ltr\">۳۴۳×۴۴</span>، گردی ۱۲، یک برچسب وسط‌چین Bold ۱۶."
      ]
    ],
    "props": [
      [
        "variant",
        "'red' | 'blue'",
        "'red'",
        "قرمز فروشندهٔ اینترنتی، آبی فروشندهٔ حضوری. <code>offline</code> نام مستعار آبی است."
      ],
      [
        "compact",
        "boolean",
        "false",
        "میان‌بر ۴۴ پیکسلی ارزان‌ترین فروشنده."
      ],
      [
        "ad",
        "boolean",
        "false",
        "نشان افشای «آگهی» را رندر می‌کند."
      ],
      [
        "seller / price",
        "string",
        "—",
        "قیمت از پیش با اعداد فارسی قالب‌بندی شده است."
      ]
    ],
    "a11y": [
      "نام دسترس‌پذیر باید قیمت، فروشنده و در صورت وجود افشای آگهی را با هم بیاورد: «۱۵٬۸۰۰٬۰۰۰ تومان، خرید از تکنولایف، آگهی».",
      "نشان آگهی متن واقعی است، نه تصویر پس‌زمینه، تا به صفحه‌خوان برسد.",
      "قیمت را بین چند عنصر نشکنید؛ صفحه‌خوان آن را دو عدد جدا می‌خواند.",
      "با ارتفاع ۷۲ پیکسل، ناحیهٔ لمس بسیار بالاتر از حداقل <span class=\"t-bidi\" dir=\"ltr\">۲۴×۲۴</span> در معیار ۲.۵.۸ است."
    ],
    "responsive": "سقف ۳۴۳ پیکسل، یعنی صفحهٔ ۳۷۵ پیکسلی منهای حاشیه‌های ۱۶ پیکسلی‌اش. زیر آن تمام‌عرض. از نقطهٔ md فروشنده و قیمت در یک خط می‌نشینند و ارتفاع ردیف به ۵۶ پیکسل می‌رسد.",
    "specimens": [
      {
        "label": "فروشندهٔ اینترنتی، تبلیغاتی",
        "canvas": "fog",
        "stageClass": "spec__stage--stack spec__stage--center",
        "html": "<button class=\"t-buybox\">\n  <span class=\"t-buybox__ad\">آگهی</span>\n  <span class=\"t-buybox__body\">\n    <span class=\"t-buybox__seller\">خرید از تکنولایف</span>\n    <span class=\"t-buybox__price\">۱۶٫۱۰۰٫۰۰۰ تومان</span>\n  </span>\n</button>\n<button class=\"t-buybox\">\n  <span class=\"t-buybox__body\">\n    <span class=\"t-buybox__seller\">خرید از دیجی‌کالا</span>\n    <span class=\"t-buybox__price\">۱۵٫۸۰۰٫۰۰۰ تومان</span>\n  </span>\n</button>"
      },
      {
        "label": "فروشندهٔ حضوری",
        "note": "آبی اینجا دکمهٔ درجه‌دو نیست. پیش از لمس به خریدار می‌گوید این خرید در فروشگاه اتفاق می‌افتد.",
        "canvas": "fog",
        "stageClass": "spec__stage--stack spec__stage--center",
        "html": "<button class=\"t-buybox t-buybox--offline\">\n  <span class=\"t-buybox__ad\">آگهی</span>\n  <span class=\"t-buybox__body\">\n    <span class=\"t-buybox__seller\">خرید از ادکلن شهر</span>\n    <span class=\"t-buybox__price\">۱۶٫۱۰۰٫۰۰۰ تومان</span>\n  </span>\n</button>\n<button class=\"t-buybox t-buybox--offline\">\n  <span class=\"t-buybox__body\">\n    <span class=\"t-buybox__seller\">خرید از موبایل ولیعصر</span>\n    <span class=\"t-buybox__price\">۱۵٫۸۰۰٫۰۰۰ تومان</span>\n  </span>\n</button>"
      },
      {
        "label": "میان‌بر ارزان‌ترین فروشنده",
        "canvas": "fog",
        "stageClass": "spec__stage--center",
        "html": "<button class=\"t-buybox t-buybox--compact\">\n  <span class=\"t-buybox__body\"><span class=\"t-buybox__seller\">خرید از ارزان‌ترین فروشنده</span></span>\n</button>"
      }
    ],
    "react": "export function BuyBoxButton({ variant = 'red', compact, ad, seller, price, ...rest }) {\n  const label = [price, seller, ad && 'آگهی'].filter(Boolean).join('، ');\n  return (\n    <button\n      className={clsx('t-buybox', variant === 'blue' && 't-buybox--offline', compact && 't-buybox--compact')}\n      aria-label={label}\n      {...rest}\n    >\n      {ad && <span className=\"t-buybox__ad\">آگهی</span>}\n      <span className=\"t-buybox__body\">\n        <span className=\"t-buybox__seller\">{seller}</span>\n        {!compact && <span className=\"t-buybox__price\">{price}</span>}\n      </span>\n    </button>\n  );\n}"
  }
];
