/* Generated by build/translate-components.mjs from source/fa/components.json.
   Prose is Farsi; specimen HTML, class names and React code are untouched.
   Edit the Farsi in source/fa/components.json, then re-run the script. */
export default [
  {
    "name": "Toast",
    "slug": "toast",
    "group": "Feedback",
    "status": "new",
    "legacy": [],
    "summary": "تأیید می‌کند که چیزی اتفاق افتاد. هرگز مسدود نمی‌کند.",
    "description": [
      "بزرگ‌ترین خلأ کیت اولیه. بیست‌ونه صفحه، و حتی یک تأیید برای کنش کاربر وجود نداشت.",
      "توست‌های ترب <strong>به پایین لنگر می‌اندازند</strong>. پیش‌فرض صنعت بالا-راست است، اما بالای صفحهٔ ترب جای جست‌وجوست و پایین همان‌جایی است که شست از قبل هست. لنگر پایین یعنی توست هرگز هدری را که کاربر با آن ناوبری می‌کند نمی‌پوشاند."
    ],
    "use": [
      "کنشی را که کاربر انجام داد تأیید کنید: «به علاقه‌مندی‌ها اضافه شد».",
      "وقتی کنش بازگشت‌پذیر است «واگرد» بدهید؛ همین است که توست را از دیالوگ بهتر می‌کند.",
      "چهار تا پنج ثانیه. برای هر چیزی که کنش دارد، بیشتر."
    ],
    "avoid": [
      "خطاهایی که نیاز به تصمیم دارند. آنجا Alert یا دیالوگ درست است.",
      "انباشتن بیش از سه تا؛ به یک شمارنده جمع کنید.",
      "توست برای چیزی که رابط از قبل نشان می‌دهد؛ اگر قلب پر شد، توست فقط نویز است."
    ],
    "anatomy": [
      [
        "ناحیه",
        "ثابت در پایین، فاصلهٔ ۱۶ پیکسلی، آگاه به ناحیهٔ امن. بالای md سقف ۳۸۰ پیکسل می‌گیرد و به انتهای محور می‌چسبد."
      ],
      [
        "توست",
        "سطح معکوس، گردی ۱۲، ارتفاع ۳."
      ],
      [
        "کنش",
        "واگرد اختیاری — زیرخط‌دار، هم‌رنگ معکوس."
      ],
      [
        "بستن",
        "هرجا کنش هست، همیشه حاضر."
      ]
    ],
    "props": [
      [
        "tone",
        "'default' | 'positive' | 'critical' | 'caution'",
        "'default'",
        ""
      ],
      [
        "title / desc",
        "string",
        "—",
        ""
      ],
      [
        "action",
        "{ label, onClick }",
        "—",
        "معمولاً واگرد."
      ],
      [
        "duration",
        "number",
        "4200",
        "میلی‌ثانیه. صفر یعنی نیازمند بستن دستی."
      ]
    ],
    "a11y": [
      "ناحیه <code>role=\"status\"</code> با <code>aria-live=\"polite\"</code> است — اعلام می‌شود بدون آنکه فوکوس را بدزدد.",
      "توست بحرانی <code>role=\"alert\"</code> و <code>aria-live=\"assertive\"</code> می‌گیرد. کم استفاده کنید؛ کار کاربر را قطع می‌کند.",
      "توستی که کنش دارد نباید پیش از آنکه کاربر صفحه‌کلید به آن برسد خودبه‌خود بسته شود — دست‌کم هشت ثانیه، یا ماندگار.",
      "هرگز تنها راه رسیدن به یک کنش را داخل توست نگذارید."
    ],
    "responsive": "روی موبایل تمام‌عرض با فاصله؛ از md عرض ۳۸۰ پیکسل چسبیده به انتهای محور. همیشه بالای ناوبری پایین.",
    "specimens": [
      {
        "label": "توست‌های زنده",
        "note": "این‌ها توست واقعی در صفحه ایجاد می‌کنند — پایین نمایشگر.",
        "canvas": "fog",
        "html": "<button class=\"t-btn t-btn--outline t-btn--md\" onclick=\"torobToast({title:'به علاقه‌مندی‌ها اضافه شد',action:'واگرد'})\">Default + undo</button>\n<button class=\"t-btn t-btn--outline t-btn--md\" onclick=\"torobToast({variant:'positive',title:'آدرس ذخیره شد',desc:'می‌توانید از حساب کاربری ویرایش کنید.'})\">Positive</button>\n<button class=\"t-btn t-btn--outline t-btn--md\" onclick=\"torobToast({variant:'critical',title:'اتصال برقرار نشد',desc:'دوباره تلاش کنید.',action:'تلاش مجدد'})\">Critical</button>\n<button class=\"t-btn t-btn--outline t-btn--md\" onclick=\"torobToast({variant:'caution',title:'موجودی این فروشگاه کم است'})\">Caution</button>"
      },
      {
        "label": "ساختار",
        "canvas": "plain",
        "html": "<div class=\"t-toast\" style=\"position:relative;max-inline-size:340px\">\n  <div class=\"t-toast__body\"><div class=\"t-toast__title\">به علاقه‌مندی‌ها اضافه شد</div><div class=\"t-toast__desc\">کازاموراتی مفیستو ۱۰۰ میل</div></div>\n  <button class=\"t-toast__action\">واگرد</button>\n  <button class=\"t-toast__close\" aria-label=\"بستن\">✕</button>\n</div>"
      }
    ],
    "react": "const ToastContext = createContext(null);\nexport const useToast = () => useContext(ToastContext);\n\nexport function ToastProvider({ children }) {\n  const [items, setItems] = useState([]);\n  const show = useCallback(t => {\n    const id = crypto.randomUUID();\n    setItems(x => [...x.slice(-2), { ...t, id }]);          // never more than three\n    const ms = t.duration ?? (t.action ? 8000 : 4200);       // actions need reachable time\n    if (ms) setTimeout(() => setItems(x => x.filter(i => i.id !== id)), ms);\n  }, []);\n  return (\n    <ToastContext.Provider value={{ show }}>\n      {children}\n      <div className=\"t-toast-region\" role=\"status\" aria-live=\"polite\">\n        {items.map(t => (\n          <div key={t.id} className={clsx('t-toast', t.tone && `t-toast--${t.tone}`)}\n               role={t.tone === 'critical' ? 'alert' : undefined}>\n            <div className=\"t-toast__body\">\n              <div className=\"t-toast__title\">{t.title}</div>\n              {t.desc && <div className=\"t-toast__desc\">{t.desc}</div>}\n            </div>\n            {t.action && <button className=\"t-toast__action\" onClick={t.action.onClick}>{t.action.label}</button>}\n            <button className=\"t-toast__close\" aria-label=\"بستن\"\n                    onClick={() => setItems(x => x.filter(i => i.id !== t.id))}>✕</button>\n          </div>\n        ))}\n      </div>\n    </ToastContext.Provider>\n  );\n}"
  },
  {
    "name": "Alert",
    "slug": "alert",
    "group": "Feedback",
    "status": "new",
    "legacy": [],
    "summary": "وضعیت سطح‌صفحه که تا حل‌نشدن می‌ماند.",
    "description": [
      "جایی که Toast می‌گذرد، Alert می‌ماند. برای شرایطی که کاربر باید هنگام کار از آنها خبر داشته باشد: قطعی سرویس، فیلد ناقص پروفایل، محدودیت ارسال در شهرش."
    ],
    "use": [
      "اول مشکل را بگویید، بعد راه جبران را — به همین ترتیب.",
      "وقتی راه‌حلی هست، آن را به‌صورت دکمه داخل هشدار بگذارید.",
      "در هر ناحیه یک هشدار. دو هشدار روی هم یعنی جای دیگری در طراحی اشتباه شده."
    ],
    "avoid": [
      "هشدار برای موفقیت — آن کار Toast است.",
      "کادر رنگی کناری ضخیم‌تر از یک خط مویی؛ زمینهٔ رنگی از قبل وضعیت را می‌رساند.",
      "هشدار قابل‌بستن برای شرایطی که پس از بستن هنوز برقرارند."
    ],
    "anatomy": [
      [
        "ظرف",
        "زمینهٔ رنگی، کادر ۱ پیکسلی هم‌رنگ، گردی ۱۲."
      ],
      [
        "آیکون",
        "هم‌فام، ۲۰ پیکسل، تراز بالا."
      ],
      [
        "بدنه",
        "عنوان Bold، سپس توضیح."
      ],
      [
        "کنش‌ها",
        "دکمه‌های اختیاری، زیر بدنه."
      ]
    ],
    "props": [
      [
        "tone",
        "'info' | 'positive' | 'caution' | 'critical' | 'guarantee'",
        "'info'",
        ""
      ],
      [
        "title / children",
        "string",
        "—",
        ""
      ],
      [
        "actions",
        "ReactNode",
        "—",
        ""
      ],
      [
        "onDismiss",
        "() => void",
        "—",
        "فقط وقتی که شرط واقعاً قابل بستن است."
      ]
    ],
    "a11y": [
      "<code>role=\"status\"</code> برای فام‌های اطلاعی؛ <code>role=\"alert\"</code> فقط برای بحرانی.",
      "آیکون <code>aria-hidden</code> است — فام از قبل در متن آمده.",
      "معیار ۳.۲.۶ نسخهٔ ۲.۲: اگر هشدار راه کمک می‌دهد، آن راه باید در همهٔ صفحه‌ها در جای یکسانی باشد."
    ],
    "responsive": "تمام‌عرض ظرف خودش. زیر ۳۷۵ پیکسل کنش‌ها تمام‌عرض می‌شوند.",
    "specimens": [
      {
        "label": "فام‌ها",
        "canvas": "fog",
        "stageClass": "spec__stage--stack",
        "html": "<div class=\"t-alert t-alert--critical\" role=\"alert\" style=\"max-inline-size:440px\">\n  <svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 1.5 15 14H1zM7.3 6v4h1.4V6zm0 5v1.4h1.4V11z\"/></svg>\n  <div class=\"t-alert__body\"><div class=\"t-alert__title\">اتصال به اینترنت برقرار نیست</div><div>نتایج نمایش‌داده‌شده مربوط به آخرین بازدید شماست.</div>\n    <div class=\"t-alert__actions\"><button class=\"t-btn t-btn--outline t-btn--sm\">تلاش مجدد</button></div>\n  </div>\n</div>\n<div class=\"t-alert t-alert--caution\" role=\"status\" style=\"max-inline-size:440px\">\n  <svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 1.5 15 14H1zM7.3 6v4h1.4V6zm0 5v1.4h1.4V11z\"/></svg><div class=\"t-alert__body\"><div class=\"t-alert__title\">ارسال به این شهر انجام نمی‌شود</div><div>می‌توانید محصول را حضوری از فروشگاه تهیه کنید.</div></div>\n</div>\n<div class=\"t-alert t-alert--guarantee\" role=\"status\" style=\"max-inline-size:440px\">\n  <svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM7 11 3.9 7.9 5 6.8 7 8.8l4-4 1.1 1.1z\"/></svg><div class=\"t-alert__body\"><div class=\"t-alert__title\">این خرید تحت ضمانت ترب است</div><div>تا ۷ روز امکان بازگشت کالا وجود دارد.</div></div>\n</div>\n<div class=\"t-alert t-alert--info\" role=\"status\" style=\"max-inline-size:440px\">\n  <svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm-.7 3h1.4v1.4H7.3zm2.2 8H6.5v-1.2h1V7.7h-1V6.5h2.2v4.3h1z\"/></svg><div class=\"t-alert__body\"><div>قیمت‌ها هر ۲۰ دقیقه به‌روزرسانی می‌شوند.</div></div>\n</div>"
      }
    ],
    "react": "export function Alert({ tone = 'info', title, actions, onDismiss, children }) {\n  return (\n    <div className={clsx('t-alert', `t-alert--${tone}`)} role={tone === 'critical' ? 'alert' : 'status'}>\n      <span className=\"t-alert__icon\" aria-hidden=\"true\">{TONE_ICON[tone]}</span>\n      <div className=\"t-alert__body\">\n        {title && <div className=\"t-alert__title\">{title}</div>}\n        <div>{children}</div>\n        {actions && <div className=\"t-alert__actions\">{actions}</div>}\n      </div>\n      {onDismiss && <IconButton size=\"sm\" label=\"بستن\" onClick={onDismiss}><CloseIcon /></IconButton>}\n    </div>\n  );\n}"
  },
  {
    "name": "EmptyState",
    "slug": "empty-state",
    "group": "Feedback",
    "status": "new",
    "legacy": [],
    "summary": "یک حالت معتبر که چیزی در آن نیست. همیشه راه خروج را نام می‌برد.",
    "description": [
      "منبع دو تا از اینها را درجا کشیده — «محصولی اضافه نشده» و «عدم اتصال محصولات به ترب» — اما هرگز به‌عنوان کامپوننت، پس هر تیمی دوباره می‌کشیدشان.",
      "قرارداد این است: <strong>حالت خالی بدون کنش یک بن‌بست است.</strong> اگر واقعاً کاری برای انجام‌دادن نیست، همین را صریح بگویید، نه اینکه سکوت کنید."
    ],
    "use": [
      "«نتیجه‌ای نبود» را از «هنوز چیزی اینجا نیست» جدا کنید؛ این دو متن و کنش متفاوت می‌خواهند.",
      "برای نبود نتیجه، شل‌ترین فیلتر را برای حذف پیشنهاد دهید.",
      "تصویر را آرام نگه دارید. یک تابلوی راهنماست، نه یک شخصیت."
    ],
    "avoid": [
      "«چیزی یافت نشد» بدون قدم بعدی.",
      "سرزنش کاربر برای ترکیب فیلتری که خود رابط اجازه‌اش را داد.",
      "یک تصویر مشترک برای خالی و خطا؛ این دو معنای متفاوتی دارند."
    ],
    "anatomy": [
      [
        "تصویر",
        "نشانهٔ اختیاری ۳۰ تا ۴۸ پیکسلی، فام غیرفعال (بحرانی برای خطا)."
      ],
      [
        "عنوان",
        "۱۶ پیکسل Bold — وضعیت را نام می‌برد."
      ],
      [
        "توضیح",
        "۱۴ پیکسل ثانویه، حداکثر ۴۶ نویسه — توضیح می‌دهد و به جلو اشاره می‌کند."
      ],
      [
        "کنش‌ها",
        "یک جبران اصلی، حداکثر یک ثانویه."
      ]
    ],
    "props": [
      [
        "variant",
        "'empty' | 'error'",
        "'empty'",
        "error تصویر را بحرانی می‌کند."
      ],
      [
        "inline",
        "boolean",
        "false",
        "فشرده، برای استفاده درون کارت."
      ],
      [
        "title / desc / action",
        "—",
        "—",
        ""
      ]
    ],
    "a11y": [
      "عنوان یک هدینگ واقعی در سطح درست جایگاهش است.",
      "وقتی نتایج پس از تغییر فیلتر خالی می‌شوند، با <code>aria-live=\"polite\"</code> اعلام کنید؛ فهرستی که بی‌صدا خالی شود خراب به نظر می‌رسد."
    ],
    "responsive": "فاصلهٔ عمودی زیر ۳۷۵ پیکسل نصف می‌شود. توضیح در هیچ اندازه‌ای از ۴۶ نویسه فراتر نمی‌رود.",
    "specimens": [
      {
        "label": "نتیجه‌ای نبود",
        "canvas": "fog",
        "html": "<div class=\"t-empty\" style=\"inline-size:100%;max-inline-size:420px\">\n  <div class=\"t-empty__art\"><svg width=\"40\" height=\"40\" viewBox=\"0 0 32 32\" fill=\"currentColor\"><path d=\"M14 3a11 11 0 1 0 6.7 19.7l6.9 7 1.4-1.4-6.9-6.9A11 11 0 0 0 14 3zm0 2.5a8.5 8.5 0 1 1 0 17 8.5 8.5 0 0 1 0-17z\"/></svg></div>\n  <div class=\"t-empty__title\">فروشگاهی با این فیلترها پیدا نشد</div>\n  <div class=\"t-empty__desc\">در شعاع ۲ کیلومتری، ۷۸ فروشگاه هست. فیلتر «باز الان» را بردارید تا همه را ببینید.</div>\n  <div class=\"t-empty__actions\">\n    <button class=\"t-btn t-btn--primary t-btn--md\">حذف فیلتر «باز الان»</button>\n    <button class=\"t-btn t-btn--ghost t-btn--md\">همه فیلترها</button>\n  </div>\n</div>"
      },
      {
        "label": "خطا",
        "canvas": "fog",
        "html": "<div class=\"t-empty t-empty--error\" style=\"inline-size:100%;max-inline-size:420px\">\n  <div class=\"t-empty__art\"><svg width=\"40\" height=\"40\" viewBox=\"0 0 32 32\" fill=\"currentColor\"><path d=\"M16 3 30 28H2zM14.6 12v8h2.8v-8zm0 10v2.8h2.8V22z\"/></svg></div>\n  <div class=\"t-empty__title\">نتوانستیم فروشگاه‌ها را بارگذاری کنیم</div>\n  <div class=\"t-empty__desc\">اتصال اینترنت را بررسی کنید و دوباره تلاش کنید. اگر مشکل ادامه داشت، چند دقیقه بعد سر بزنید.</div>\n  <div class=\"t-empty__actions\"><button class=\"t-btn t-btn--primary t-btn--md\">تلاش مجدد</button></div>\n  <div class=\"t-empty__code\">ERR_NEARBY_TIMEOUT</div>\n</div>"
      }
    ],
    "react": "export function EmptyState({ variant = 'empty', inline, art, title, desc, action, code }) {\n  return (\n    <div className={clsx('t-empty', variant === 'error' && 't-empty--error', inline && 't-empty--inline')}>\n      {art && <div className=\"t-empty__art\" aria-hidden=\"true\">{art}</div>}\n      <div className=\"t-empty__title\">{title}</div>\n      {desc && <div className=\"t-empty__desc\">{desc}</div>}\n      {action && <div className=\"t-empty__actions\">{action}</div>}\n      {code && <div className=\"t-empty__code\">{code}</div>}\n    </div>\n  );\n}"
  },
  {
    "name": "Skeleton",
    "slug": "skeleton",
    "group": "Feedback",
    "status": "new",
    "legacy": [],
    "summary": "شکل محتوایی را نگه می‌دارد که هنوز نرسیده.",
    "description": [
      "اسکلتی که با چیدمان واقعی نخواند بدتر از اسپینر است؛ وقتی محتوا می‌رسد صفحه می‌پرد. اسکلت‌ها را از همان ابزارهای چیدمان کامپوننت واقعی بسازید."
    ],
    "use": [
      "برای محتوایی که شکلش را از پیش می‌دانید: کارت، فهرست، جدول.",
      "ابعاد را دقیقاً با عنصر واقعی یکی کنید.",
      "فقط بعد از حدود ۲۰۰ میلی‌ثانیه نشان دهید؛ سریع‌تر از آن چشمک می‌زند."
    ],
    "avoid": [
      "اسکلت برای محتوای با شکل نامعلوم. آنجا اسپینر درست است.",
      "درخشش روی بیش از حدود یک صفحه؛ به نویز بصری تبدیل می‌شود.",
      "اسکلتی که از چیزی که جایش را می‌گیرد بلندتر یا کوتاه‌تر است."
    ],
    "anatomy": [
      [
        "بلوک",
        "گرادیان ملایم تا فرورفته، درخشش ۱٫۴ ثانیه‌ای، گردی ۸ (۴ برای متن)."
      ]
    ],
    "props": [
      [
        "variant",
        "'block' | 'text' | 'title' | 'circle'",
        "'block'",
        ""
      ]
    ],
    "a11y": [
      "ظرف <code>aria-busy=\"true\"</code> می‌گیرد؛ خود اسکلت‌ها <code>aria-hidden</code> هستند.",
      "پایان بارگذاری را یک بار با <code>aria-live=\"polite\"</code> اعلام کنید، نه به‌ازای هر آیتم.",
      "درخشش زیر <code>prefers-reduced-motion</code> کاملاً متوقف می‌شود."
    ],
    "responsive": "رفتار واکنش‌گرای کامپوننت واقعی را به ارث می‌برد، چون از همان کلاس‌های چیدمان استفاده می‌کند.",
    "specimens": [
      {
        "label": "اسکلت کارت فروشگاه",
        "canvas": "plain",
        "html": "<div class=\"t-store-card\" aria-busy=\"true\" style=\"max-inline-size:340px;border-radius:12px\">\n  <div class=\"t-store-card__head\">\n    <div class=\"t-store-card__logo t-skeleton\"></div>\n    <div class=\"t-store-card__body\" style=\"gap:6px\">\n      <div class=\"t-skeleton t-skeleton--title\" style=\"inline-size:58%\"></div>\n      <div class=\"t-skeleton t-skeleton--text\" style=\"inline-size:76%\"></div>\n    </div>\n  </div>\n  <div class=\"t-store-card__rail\">\n    <div><div class=\"t-thumb t-thumb--sm t-skeleton\"></div></div>\n    <div><div class=\"t-thumb t-thumb--sm t-skeleton\"></div></div>\n    <div><div class=\"t-thumb t-thumb--sm t-skeleton\"></div></div>\n  </div>\n</div>"
      }
    ],
    "react": "export function Skeleton({ variant = 'block', width, height, className }) {\n  return <div className={clsx('t-skeleton', variant !== 'block' && `t-skeleton--${variant}`, className)}\n              style={{ inlineSize: width, blockSize: height }} aria-hidden=\"true\" />;\n}"
  },
  {
    "name": "Spinner",
    "slug": "spinner",
    "group": "Feedback",
    "status": "new",
    "legacy": [],
    "summary": "انتظار نامعین برای محتوای با شکل نامعلوم.",
    "description": [
      "اسپینر را فقط جایی به کار ببرید که اسکلت کار نمی‌کند، چون شکل آنچه در راه است را نمی‌دانید."
    ],
    "use": [
      "داخل دکمه هنگام ثبت (خود Button این را مدیریت می‌کند).",
      "تمام‌صفحه فقط برای عملیات مسدودکننده‌ای که کاربر شروع کرده."
    ],
    "avoid": [
      "اسپینر جایی که چیدمان معلوم است — آنجا Skeleton درست است.",
      "اسپینر بی‌سقف. پس از حدود ده ثانیه به خطا با دکمهٔ تلاش مجدد سوئیچ کنید."
    ],
    "anatomy": [
      [
        "حلقه",
        "۲۰ پیکسل پیش‌فرض، ۲ پیکسل ضخامت، بالای آبی روی حلقهٔ کادر پیش‌فرض، ۶۲۰ میلی‌ثانیه خطی."
      ]
    ],
    "props": [
      [
        "size",
        "'sm' | 'md' | 'lg'",
        "'md'",
        "۱۴ / ۲۰ / ۳۲ پیکسل."
      ]
    ],
    "a11y": [
      "درون <code>role=\"status\"</code> با یک «در حال بارگذاری» بصری‌پنهان بپیچید.",
      "زیر <code>prefers-reduced-motion</code> چرخش کند می‌شود، نه اینکه بایستد؛ اسپینر یخ‌زده مثل صفحهٔ کرش‌کرده خوانده می‌شود."
    ],
    "responsive": "اندازه‌های ثابت.",
    "specimens": [
      {
        "label": "اندازه‌ها",
        "canvas": "fog",
        "html": "<span class=\"t-spinner t-spinner--sm\"></span><span class=\"t-spinner\"></span><span class=\"t-spinner t-spinner--lg\"></span>\n<div role=\"status\" style=\"display:flex;align-items:center;gap:8px\"><span class=\"t-spinner\"></span><span class=\"t-body-md t-tone-secondary\">در حال بارگذاری فروشگاه‌ها…</span></div>"
      }
    ],
    "react": "export function Spinner({ size = 'md', label = 'در حال بارگذاری' }) {\n  return (\n    <span role=\"status\">\n      <span className={clsx('t-spinner', size !== 'md' && `t-spinner--${size}`)} />\n      <span className=\"t-visually-hidden\">{label}</span>\n    </span>\n  );\n}"
  }
];
