/* Generated by build/translate-components.mjs from source/fa/components.json.
   Prose is Farsi; specimen HTML, class names and React code are untouched.
   Edit the Farsi in source/fa/components.json, then re-run the script. */
export default [
  {
    "name": "SegmentedControl",
    "slug": "segmented-control",
    "group": "Navigation",
    "status": "revised",
    "legacy": [
      "Segmented Controls/Selected",
      "Segmented Controls/Not-selected",
      "Segmented Controls/Icon Selected",
      "Segmented Controls/Icon Not-selected",
      "Segmented Controls/Light/Large/Selected"
    ],
    "summary": "محتوای پایین را بین نماهای متقابلاً ناسازگار جابه‌جا می‌کند.",
    "description": [
      "پنج مستر در کیت اولیه که فقط در حالت انتخاب، وجود آیکون و اندازه فرق داشتند. یک کامپوننت، سه پراپ. توجه کنید که چهار مستر هم‌نام <code>Segmented Controls/Selected</code> با شناسه‌های متفاوت وجود دارد.",
      "نسخهٔ بزرگ <span class=\"t-bidi\" dir=\"ltr\">۳۹۵×۶۴</span> یک تراکم دیگر است، نه کامپوننت دیگر: <code>size=\"lg\"</code>."
    ],
    "use": [
      "دو تا پنج گزینه که همه بدون اسکرول جا شوند.",
      "تعویض نما — فروشگاه‌ها ⇄ محصولات — نه فیلترکردن آن.",
      "شیشه‌ای، تا بتواند روی نقشه یا فهرست در حال اسکرول شناور بماند."
    ],
    "avoid": [
      "بیش از پنج گزینه. آنجا Tabs درست است.",
      "گزینه‌هایی که برچسبشان بریده می‌شود.",
      "به‌عنوان فیلتر. فیلترها روی هم جمع می‌شوند، سگمنت‌ها ناسازگارند."
    ],
    "anatomy": [
      [
        "ریل",
        "شیشه، گردی ۱۲، فاصلهٔ ۳ پیکسلی، در نهایت اسکرول افقی."
      ],
      [
        "آیتم",
        "۲۶ پیکسل (۴۴ در lg)، ۱۲ پیکسل Bold، گردی ۸."
      ],
      [
        "انتخاب‌شده",
        "شیشه در سطح ۶۰٪ با حلقهٔ آبی ۰٫۵ پیکسلی."
      ]
    ],
    "props": [
      [
        "options",
        "{ value, label, icon?, count? }[]",
        "—",
        "دو تا پنج."
      ],
      [
        "value",
        "string",
        "—",
        "کنترل‌شده."
      ],
      [
        "size",
        "'md' | 'lg'",
        "'md'",
        "ریل ۳۲ / ۶۴ پیکسل."
      ],
      [
        "block",
        "boolean",
        "false",
        "گزینه‌ها عرض را به‌طور مساوی تقسیم می‌کنند."
      ]
    ],
    "a11y": [
      "<code>role=\"tablist\"</code> با <code>role=\"tab\"</code> و <code>aria-selected</code>، متصل به پنل با <code>aria-controls</code>.",
      "کلیدهای جهت حرکت می‌کنند و کل گروه یک توقف‌گاه Tab است."
    ],
    "responsive": "تا md عرض ذاتی؛ زیر آن <code>block</code> تا گزینه‌ها ردیف را پر کنند. هرگز به خط بعد نمی‌رود، اسکرول می‌شود.",
    "specimens": [
      {
        "label": "فروشگاه‌ها / محصولات",
        "canvas": "map",
        "stageClass": "spec__stage--center",
        "html": "<div class=\"t-segmented\" role=\"tablist\" aria-label=\"نمای اطراف\">\n  <button class=\"t-segmented__item\" role=\"tab\" aria-selected=\"true\">فروشگاه‌ها<span class=\"t-chip__count\">۴۳</span></button>\n  <button class=\"t-segmented__item\" role=\"tab\" aria-selected=\"false\">محصولات<span class=\"t-chip__count\">۵۵</span></button>\n</div>"
      },
      {
        "label": "بزرگ، تمام‌عرض",
        "canvas": "fog",
        "html": "<div class=\"t-segmented t-segmented--lg t-segmented--block\" role=\"tablist\" aria-label=\"مرتب‌سازی\" style=\"max-inline-size:360px\">\n  <button class=\"t-segmented__item\" role=\"tab\" aria-selected=\"true\">نزدیک‌ترین</button>\n  <button class=\"t-segmented__item\" role=\"tab\" aria-selected=\"false\">ارزان‌ترین</button>\n  <button class=\"t-segmented__item\" role=\"tab\" aria-selected=\"false\">محبوب‌ترین</button>\n</div>"
      }
    ],
    "react": "export function SegmentedControl({ options, value, onChange, size = 'md', block, label }) {\n  return (\n    <div className={clsx('t-segmented', size === 'lg' && 't-segmented--lg', block && 't-segmented--block')}\n         role=\"tablist\" aria-label={label}>\n      {options.map(o => (\n        <button key={o.value} className=\"t-segmented__item\" role=\"tab\"\n                aria-selected={o.value === value} onClick={() => onChange(o.value)}>\n          {o.icon}{o.label}{o.count != null && <span className=\"t-chip__count\">{toFa(o.count)}</span>}\n        </button>\n      ))}\n    </div>\n  );\n}"
  },
  {
    "name": "FilterChip",
    "slug": "filter-chip",
    "group": "Navigation",
    "status": "revised",
    "legacy": [
      "Filter/Cell/Cell",
      "Filter/Cell/Icon",
      "Filter/Cell/Icon+Chevron",
      "city filter",
      "official seller"
    ],
    "summary": "یک وجه از فیلتر. یا روشن می‌شود یا برگه‌ای از گزینه‌ها باز می‌کند.",
    "description": [
      "سه مستر سلول در کیت، به‌علاوهٔ دو مورد مستندنشده که فقط در صفحهٔ نمونه‌ها پیدا می‌شوند — <code>city filter</code> و <code>official seller</code>. این دو هرگز در کتابخانهٔ کامپوننت نبودند و دقیقاً همان فاصله‌ای است که این سیستم برای بستنش وجود دارد.",
      "دو رفتار یک شکل مشترک دارند: تراشهٔ <strong>دوحالته</strong> همان‌جا روشن و خاموش می‌شود؛ تراشهٔ <strong>بازکننده</strong> شورون دارد و یک برگه باز می‌کند. شورون یک قرارداد است — هرگز روی تراشه‌ای که چیزی باز نمی‌کند شورون نگذارید."
    ],
    "use": [
      "روی وجه‌های چندمقداری تعداد فعال را نشان دهید: «برند ۳».",
      "فیلترهای اعمال‌شده را دیده‌شونده نگه دارید؛ هرگز آنها را در «۳ فیلتر» جمع نکنید.",
      "به ترتیب میزان استفاده مرتب کنید، نه الفبایی."
    ],
    "avoid": [
      "شورون روی تراشه‌ای که فقط دوحالته است.",
      "بیش از حدود هشت تراشه پیش از ورودی «همهٔ فیلترها».",
      "حذف تراشه از ریل چون غیرفعال است؛ ریل باید پایدار بماند."
    ],
    "anatomy": [
      [
        "ظرف",
        "۳۲ پیکسل، گردی ۱۲، شیشه. حالت انتخاب به ۶۰٪ با حلقهٔ آبی می‌رود."
      ],
      [
        "آیکون آغازین",
        "اختیاری ۱۶ پیکسل."
      ],
      [
        "برچسب و تعداد",
        "۱۲ پیکسل Bold؛ تعداد ثانویه است."
      ],
      [
        "شورون",
        "فقط وقتی که تراشه برگه‌ای باز می‌کند. هرگز روی تراشه‌ای که فقط دوحالته است."
      ]
    ],
    "props": [
      [
        "active",
        "boolean",
        "false",
        "حالت انتخاب."
      ],
      [
        "count",
        "number",
        "—",
        "مقادیر اعمال‌شده روی وجه چندانتخابی."
      ],
      [
        "opens",
        "boolean",
        "false",
        "شورون را رندر و <code>aria-haspopup</code> را تنظیم می‌کند."
      ]
    ],
    "a11y": [
      "تراشهٔ دوحالته <code>aria-pressed</code> می‌گیرد. تراشهٔ بازکننده <code>aria-expanded</code> و <code>aria-haspopup=\"dialog\"</code>. هرگز هر دو با هم.",
      "نام دسترس‌پذیر شامل تعداد است: «برند، ۳ مورد انتخاب شده»."
    ],
    "responsive": "در هر اندازه اسکرول افقی؛ تراشه‌ها هرگز به خط بعد نمی‌روند. ریل تا لبهٔ نمایشگر ادامه می‌یابد تا تراشهٔ نیمه‌دیده نشان دهد ادامه دارد.",
    "specimens": [
      {
        "label": "ریل فیلتر",
        "canvas": "plain",
        "html": "<div class=\"t-filter-bar\" style=\"border-radius:12px\">\n  <button class=\"t-icon-btn t-icon-btn--sm t-filter-bar__lead\" aria-label=\"همه فیلترها\"><svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M18,28H14a2,2,0,0,1-2-2V18.41L4.59,11A2,2,0,0,1,4,9.59V6A2,2,0,0,1,6,4H26a2,2,0,0,1,2,2V9.59A2,2,0,0,1,27.41,11L20,18.41V26A2,2,0,0,1,18,28ZM6,6V9.59l8,8V26h4V17.59l8-8V6Z\"/></svg></button>\n  <button class=\"t-chip\" aria-pressed=\"true\">تهران</button>\n  <button class=\"t-chip\" aria-expanded=\"false\" aria-haspopup=\"dialog\">برند<span class=\"t-chip__count\">۳</span><svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M8 11 3 6 3.7 5.3 8 9.6 12.3 5.3 13 6z\"/></svg></button>\n  <button class=\"t-chip\" aria-expanded=\"false\" aria-haspopup=\"dialog\">قیمت<svg class=\"t-icon t-icon--sm\" viewBox=\"0 0 16 16\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M8 11 3 6 3.7 5.3 8 9.6 12.3 5.3 13 6z\"/></svg></button>\n  <button class=\"t-chip\" aria-pressed=\"true\">ضمانت ترب</button>\n  <button class=\"t-chip\" aria-pressed=\"false\">نمایندگی رسمی</button>\n  <button class=\"t-chip\" aria-pressed=\"false\">باز الان</button>\n</div>",
        "note": "تراشه‌ها زنده‌اند — برای تغییر وضعیت کلیک کنید. ریل را افقی اسکرول کنید."
      }
    ],
    "react": "export function FilterChip({ active, count, opens, icon, children, ...rest }) {\n  return (\n    <button className=\"t-chip\"\n            {...(opens ? { 'aria-expanded': !!active, 'aria-haspopup': 'dialog' } : { 'aria-pressed': !!active })}\n            {...rest}>\n      {icon}{children}\n      {count != null && <span className=\"t-chip__count\">{toFa(count)}</span>}\n      {opens && <ChevronDown className=\"t-icon t-icon--sm\" />}\n    </button>\n  );\n}"
  },
  {
    "name": "Tabs",
    "slug": "tabs",
    "group": "Navigation",
    "status": "revised",
    "legacy": [
      "Tab/Selected"
    ],
    "summary": "بین بخش‌های یک صفحه جابه‌جا می‌شود. از پنج گزینه فراتر می‌رود.",
    "description": [
      "جایی که SegmentedControl یک کلید فشردهٔ ناسازگار است، Tabs همان کار را در سطح صفحه انجام می‌دهد: اسکرول می‌شود، تعداد نشان می‌دهد و به‌جای قرص پرشده یک زیرخط دارد."
    ],
    "use": [
      "بخش‌های صفحهٔ محصول: فروشنده‌ها · مشخصات · نظرات.",
      "جایی که عدد به تصمیم کمک می‌کند تعداد را نشان دهید.",
      "وقتی نوار اسکرول می‌شود، تب انتخاب‌شده را در دید نگه دارید."
    ],
    "avoid": [
      "تب‌هایی که صفحه را عوض می‌کنند نه بخش را؛ آن ناوبری است.",
      "نوار تب تودرتو.",
      "بیش از حدود هفت تب."
    ],
    "anatomy": [
      [
        "نوار",
        "خط مویی پایین، اسکرول افقی، اسکرول‌بار پنهان."
      ],
      [
        "تب",
        "۱۴ پیکسل Bold، فاصلهٔ عمودی ۱۲ پیکسل."
      ],
      [
        "نشانگر",
        "زیرخط ۲ پیکسلی برند که در ۲۲۰ میلی‌ثانیه از صفر باز می‌شود."
      ]
    ],
    "props": [
      [
        "options",
        "{ value, label, count? }[]",
        "—",
        ""
      ],
      [
        "value",
        "string",
        "—",
        "کنترل‌شده."
      ]
    ],
    "a11y": [
      "الگوی کامل tablist با <code>aria-controls</code> روی هر تب و <code>aria-labelledby</code> روی هر پنل.",
      "کلیدهای جهت حرکت می‌کنند، Home و End می‌پرند. پنل‌ها <code>tabindex=\"0\"</code> دارند تا محتوایشان قابل دسترسی باشد."
    ],
    "responsive": "در هر اندازه اسکرول افقی. بالای lg اگر همهٔ تب‌ها جا شوند، نوار به ابتدای محور می‌چسبد به‌جای کش‌آمدن.",
    "specimens": [
      {
        "label": "بخش‌های صفحهٔ محصول",
        "canvas": "fog",
        "html": "<div class=\"t-tabs\" role=\"tablist\" aria-label=\"بخش‌های محصول\" style=\"inline-size:100%\">\n  <button class=\"t-tab\" role=\"tab\" aria-selected=\"true\">فروشنده‌ها<span class=\"t-tab__count\">۷۹</span></button>\n  <button class=\"t-tab\" role=\"tab\" aria-selected=\"false\">مشخصات</button>\n  <button class=\"t-tab\" role=\"tab\" aria-selected=\"false\">نمودار قیمت</button>\n  <button class=\"t-tab\" role=\"tab\" aria-selected=\"false\">نظرات<span class=\"t-tab__count\">۱۲</span></button>\n</div>"
      }
    ],
    "react": "export function Tabs({ options, value, onChange, label }) {\n  return (\n    <div className=\"t-tabs\" role=\"tablist\" aria-label={label}>\n      {options.map(o => (\n        <button key={o.value} className=\"t-tab\" role=\"tab\" id={`tab-${o.value}`}\n                aria-selected={o.value === value} aria-controls={`panel-${o.value}`}\n                tabIndex={o.value === value ? 0 : -1} onClick={() => onChange(o.value)}>\n          {o.label}{o.count != null && <span className=\"t-tab__count\">{toFa(o.count)}</span>}\n        </button>\n      ))}\n    </div>\n  );\n}"
  },
  {
    "name": "PageHeader",
    "slug": "page-header",
    "group": "Navigation",
    "status": "revised",
    "legacy": [
      "Header/Profile"
    ],
    "summary": "هدر چسبان شیشه‌ای: بازگشت، عنوان، کنش‌ها.",
    "description": [
      "کیت اولیه یک <code>Header/Profile</code> در ابعاد <span class=\"t-bidi\" dir=\"ltr\">۳۴۳×۵۶</span> داشت که دو بار تکرار شده بود. اینجا تعمیم یافته: یک راه بازگشت، یک عنوان با زیرعنوان اختیاری و کنش‌های انتهایی."
    ],
    "use": [
      "بالای هر صفحهٔ اسکرول‌شونده بچسبانید.",
      "موقعیت و تعداد نتیجه را در زیرعنوان بگذارید: «تهران، ۷۸ مورد».",
      "کنش‌های انتهایی را به دو تا محدود کنید؛ بقیه به منو بروند."
    ],
    "avoid": [
      "دکمهٔ بازگشت در صفحهٔ ریشه.",
      "عنوان‌هایی که بریده می‌شوند؛ به‌جایش متن را کوتاه کنید."
    ],
    "anatomy": [
      [
        "ظرف",
        "۵۶ پیکسل، سطح شیشه، چسبان، خط مویی پایین."
      ],
      [
        "آغاز",
        "بازگشت یا بستن. شورون بازگشت در راست‌چین قرینه می‌شود."
      ],
      [
        "بلوک عنوان",
        "۱۶ پیکسل Bold به‌علاوهٔ ۱۲ پیکسل ثانویهٔ اختیاری."
      ],
      [
        "انتها",
        "حداکثر دو دکمهٔ آیکونی."
      ]
    ],
    "props": [
      [
        "title / subtitle",
        "string",
        "—",
        ""
      ],
      [
        "onBack",
        "() => void",
        "—",
        "در صفحهٔ ریشه حذفش کنید."
      ],
      [
        "actions",
        "ReactNode",
        "—",
        "حداکثر دو تا."
      ]
    ],
    "a11y": [
      "یک <code>&lt;header&gt;</code> واقعی با عنوان به‌عنوان <code>&lt;h1&gt;</code> صفحه‌ای که سرش را می‌گیرد.",
      "بازگشت یک دکمه با <code>aria-label=\"بازگشت\"</code> است، نه یک نشانهٔ برهنه.",
      "معیار ۲.۴.۱۱ نسخهٔ ۲.۲: هدر چسبان نباید عنصری را که تازه فوکوس گرفته بپوشاند؛ <code>scroll-padding-block-start</code> این را تضمین می‌کند."
    ],
    "responsive": "در همه‌جا ۵۶ پیکسل. بالای lg عنوان کنار مسیر راهنما می‌نشیند و اگر صفحه کوتاه باشد هدر از حالت چسبان خارج می‌شود.",
    "specimens": [
      {
        "label": "هدر",
        "canvas": "map",
        "stageClass": "spec__stage--stack",
        "html": "<header class=\"t-page-header\" style=\"border-radius:12px;position:relative;inline-size:100%\">\n  <button class=\"t-icon-btn t-icon-btn--sm\" aria-label=\"بازگشت\"><svg class=\"t-icon t-icon--directional\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M10 16 20 6 21.4 7.4 12.8 16 21.4 24.6 20 26z\"/></svg></button>\n  <div class=\"t-page-header__title\">فروشگاه‌های اطراف<div class=\"t-page-header__sub\">تهران، ۷۸ مورد</div></div>\n  <button class=\"t-icon-btn t-icon-btn--sm\" aria-label=\"اشتراک‌گذاری\"><svg class=\"t-icon\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M23,20a5,5,0,0,0-3.89,1.89L11.8,17.32a4.46,4.46,0,0,0,0-2.64l7.31-4.57A5,5,0,1,0,18,7a4.79,4.79,0,0,0,.2,1.32l-7.31,4.57a5,5,0,1,0,0,6.22l7.31,4.57A4.79,4.79,0,0,0,18,25a5,5,0,1,0,5-5ZM23,4a3,3,0,1,1-3,3A3,3,0,0,1,23,4ZM7,19a3,3,0,1,1,3-3A3,3,0,0,1,7,19Zm16,9a3,3,0,1,1,3-3A3,3,0,0,1,23,28Z\"/></svg></button>\n</header>"
      }
    ],
    "react": "export function PageHeader({ title, subtitle, onBack, actions }) {\n  return (\n    <header className=\"t-page-header\">\n      {onBack && <IconButton size=\"sm\" label=\"بازگشت\" onClick={onBack}><ChevronStart className=\"t-icon--directional\" /></IconButton>}\n      <div className=\"t-page-header__title\">\n        {title}\n        {subtitle && <div className=\"t-page-header__sub\">{subtitle}</div>}\n      </div>\n      {actions}\n    </header>\n  );\n}"
  },
  {
    "name": "BottomNav",
    "slug": "bottom-nav",
    "group": "Navigation",
    "status": "new",
    "legacy": [],
    "summary": "ناوبری سطح ریشه، لنگرانداخته جایی که شست هست.",
    "description": [
      "با اینکه همهٔ صفحه‌های نمونه موبایل بودند، در کیت وجود نداشت. شیشه‌ای، آگاه به ناحیهٔ امن، سه تا پنج مقصد."
    ],
    "use": [
      "سه تا پنج مقصد سطح‌بالا که هرگز تغییر نمی‌کنند.",
      "همهٔ آیتم‌ها را برچسب بزنید؛ آیکون تنها حدس زدن است.",
      "مقصد جاری را با <code>aria-current=\"page\"</code> مشخص کنید."
    ],
    "avoid": [
      "بیش از پنج آیتم.",
      "کنش به‌جای مقصد. دکمهٔ «+» که برگه باز می‌کند جای دیگری دارد.",
      "پنهان‌کردنش هنگام اسکرول؛ مجموعهٔ مقصدها باید ثابت باشد."
    ],
    "anatomy": [
      [
        "ظرف",
        "شیشه، چسبان به پایین، خط مویی بالا، فاصله‌دار برای نشانگر خانه."
      ],
      [
        "آیتم",
        "آیکون روی برچسب ۱۲ پیکسلی، حداقل ۴۴ پیکسل، عرض برابر."
      ],
      [
        "جاری",
        "رنگ برند و وزن Bold — دو کانال، نه فقط رنگ."
      ]
    ],
    "props": [
      [
        "items",
        "{ href, label, icon }[]",
        "—",
        "سه تا پنج."
      ],
      [
        "current",
        "string",
        "—",
        "برابر با href مقصد."
      ]
    ],
    "a11y": [
      "یک ناحیهٔ <code>&lt;nav&gt;</code> با نام دسترس‌پذیر.",
      "مقصد جاری <code>aria-current=\"page\"</code> می‌گیرد، به‌علاوهٔ وزن و رنگ تا فقط به فام تکیه نکند."
    ],
    "responsive": "فقط موبایل. از md جایش را به نوار کناری یا ناوبری بالا می‌دهد؛ هرگز هر دو را با هم رندر نکنید.",
    "specimens": [
      {
        "label": "ناوبری پایین",
        "canvas": "fog",
        "html": "<nav class=\"t-bottom-nav\" aria-label=\"ناوبری اصلی\" style=\"border-radius:12px;position:relative;inline-size:100%;max-inline-size:375px\">\n  <button class=\"t-bottom-nav__item\" aria-current=\"page\"><svg class=\"t-icon\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M16.6123,2.2138a1.01,1.01,0,0,0-1.2427,0L1,13.4194l1.2427,1.5717L4,13.6209V26a2.0041,2.0041,0,0,0,2,2H26a2.0037,2.0037,0,0,0,2-2V13.63L29.7573,15,31,13.4282ZM18,26H14V18h4Zm2,0V18a2.0023,2.0023,0,0,0-2-2H14a2.002,2.002,0,0,0-2,2v8H6V12.0615l10-7.79,10,7.8005V26Z\"/></svg>خانه</button>\n  <button class=\"t-bottom-nav__item\"><svg class=\"t-icon\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M29,27.5859l-7.5521-7.5521a11.0177,11.0177,0,1,0-1.4141,1.4141L27.5859,29ZM4,13a9,9,0,1,1,9,9A9.01,9.01,0,0,1,4,13Z\"/></svg>جستجو</button>\n  <button class=\"t-bottom-nav__item\"><svg class=\"t-icon\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M16,2A11.0134,11.0134,0,0,0,5,13a10.8885,10.8885,0,0,0,2.2163,6.6s.3.3945.3482.4517L16,30l8.439-9.9526c.0444-.0533.3447-.4478.3447-.4478l.0015-.0024A10.8846,10.8846,0,0,0,27,13,11.0134,11.0134,0,0,0,16,2Zm0,15a4,4,0,1,1,4-4A4.0045,4.0045,0,0,1,16,17Z\"/><circle cx=\"16\" cy=\"13\" r=\"4\" fill=\"none\"/></svg>اطراف من</button>\n  <button class=\"t-bottom-nav__item\"><svg class=\"t-icon\" viewBox=\"0 0 32 32\" fill=\"currentColor\" aria-hidden=\"true\"><path d=\"M16,8a5,5,0,1,0,5,5A5,5,0,0,0,16,8Zm0,8a3,3,0,1,1,3-3A3.0034,3.0034,0,0,1,16,16Z\"/><path d=\"M16,2A14,14,0,1,0,30,16,14.0158,14.0158,0,0,0,16,2ZM10,26.3765V25a3.0033,3.0033,0,0,1,3-3h6a3.0033,3.0033,0,0,1,3,3v1.3765a11.8989,11.8989,0,0,1-12,0Zm13.9925-1.4507A5.0016,5.0016,0,0,0,19,20H13a5.0016,5.0016,0,0,0-4.9925,4.9258,12,12,0,1,1,15.985,0Z\"/></svg>حساب من</button>\n</nav>"
      }
    ],
    "react": "export function BottomNav({ items, current, label = 'ناوبری اصلی' }) {\n  return (\n    <nav className=\"t-bottom-nav\" aria-label={label}>\n      {items.map(i => (\n        <a key={i.href} href={i.href} className=\"t-bottom-nav__item\"\n           aria-current={i.href === current ? 'page' : undefined}>\n          {i.icon}{i.label}\n        </a>\n      ))}\n    </nav>\n  );\n}"
  },
  {
    "name": "Breadcrumb",
    "slug": "breadcrumb",
    "group": "Navigation",
    "status": "new",
    "legacy": [],
    "summary": "این صفحه کجای درخت دسته‌بندی است.",
    "description": [
      "درخت دسته‌بندی ترب عمیق است و بالای md برای نشان‌دادنش جا هست. جداکننده باید در جهت خواندن اشاره کند؛ در راست‌چین به چپ."
    ],
    "use": [
      "صفحه‌های دسته‌بندی و صفحهٔ محصول، از md به بالا.",
      "وسط را کوتاه کنید، نه دو سر را: اولی … دو تای آخر."
    ],
    "avoid": [
      "مسیر راهنما به‌عنوان تنها راه بازگشت روی موبایل. دکمهٔ بازگشت بگذارید.",
      "لینک‌کردن صفحهٔ جاری."
    ],
    "anatomy": [
      [
        "آیتم",
        "۱۲ پیکسل ثانویه؛ صفحهٔ جاری با وزن پیش‌فرض Bold."
      ],
      [
        "جداکننده",
        "یک شورون منطقی که با جهت قرینه می‌شود."
      ]
    ],
    "props": [
      [
        "items",
        "{ href, label }[]",
        "—",
        "آخرین آیتم صفحهٔ جاری است."
      ]
    ],
    "a11y": [
      "<code>&lt;nav aria-label=\"مسیر\"&gt;</code> که یک <code>&lt;ol&gt;</code> را در بر می‌گیرد.",
      "آخرین آیتم <code>aria-current=\"page\"</code> می‌گیرد و لینک نیست."
    ],
    "responsive": "زیر md پنهان است، جایی که دکمهٔ بازگشت PageHeader کار را انجام می‌دهد.",
    "specimens": [
      {
        "label": "مسیر راهنما",
        "canvas": "fog",
        "html": "<nav class=\"t-breadcrumb\" aria-label=\"مسیر\">\n  <a class=\"t-breadcrumb__item\" href=\"#\">خانه</a><span class=\"t-breadcrumb__sep\">›</span>\n  <a class=\"t-breadcrumb__item\" href=\"#\">آرایشی و بهداشتی</a><span class=\"t-breadcrumb__sep\">›</span>\n  <a class=\"t-breadcrumb__item\" href=\"#\">عطر و ادکلن</a><span class=\"t-breadcrumb__sep\">›</span>\n  <span class=\"t-breadcrumb__item\" aria-current=\"page\">کازاموراتی مفیستو</span>\n</nav>"
      }
    ],
    "react": "export function Breadcrumb({ items }) {\n  return (\n    <nav className=\"t-breadcrumb\" aria-label=\"مسیر\">\n      <ol style={{ display: 'contents' }}>\n        {items.map((it, i) => {\n          const last = i === items.length - 1;\n          return (\n            <li key={it.href} style={{ display: 'contents' }}>\n              {last ? <span className=\"t-breadcrumb__item\" aria-current=\"page\">{it.label}</span>\n                    : <><a className=\"t-breadcrumb__item\" href={it.href}>{it.label}</a>\n                        <span className=\"t-breadcrumb__sep\" aria-hidden=\"true\">›</span></>}\n            </li>\n          );\n        })}\n      </ol>\n    </nav>\n  );\n}"
  }
];
